### ISSUE TITLE
Document VM portability issues 

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/virtualbox-remote-snapshots#20]
For example, it may be beneficial to run `VBoxManage modifyvm <VMName> --cpuid-portability-level 3` if running virtual machines are to be restored on a different host.

**Comment by PythonNut** [comment]
Now that I have access to an AMD processor, this is newly relevant to me.

**Comment by georgemarselis-nvi** [comment]
Sorry to bother you, but have you figured out what --cpuid-portability-level is all about? the manual is not informative.
